### ISSUE TITLE
Wybrać dowolny temat lekcji z fizyki (Proponuje jakiś łatwy temat, który oboje znamy)

### ISSUE THREAD

**Issue by TatusFilipek** [AntekAdamus/Projekthtml#12]
Temat lekcji z fizyki (Chyba z 8 klasy)

**Comment by AntekAdamus** [comment]
Może zrobimy w https://fritzing.org obwody elektryczne jakie robiliśmy na fizyke opiszemy je i wkleimy na strone. Możemy też nagrać filmik z działania tych obwodów i wrzucić na yt a następnie osadzić wideo na naszej stronie https://support.google.com/youtube/answer/171780?hl=en

**Comment by TatusFilipek** [comment]
Pochump ten temat mi pasuje
